### ISSUE TITLE
Ship mra-tools-c?

### ISSUE THREAD

**Issue by hadess** [flathub/io.github.neil_morrison44.pocket-sync#78]
Could we ship https://github.com/sebdel/mra-tools-c/ and the MRA files from https://github.com/jotego/jtbin/tree/master/mra in the Flatpak?

That would make it easier for folks to install arcade games to use with Jotego cores.

@neil-morrison44 opinion?

**Comment by neil-morrison44** [comment]
I think most folks use the "required files" feature to download pre-built ones (...after stating that they're legally ok to in their region etc)

Previously any time the MRA bits (or the Game & Watch ROM tools) have been too user facing always results in a massive volume of support requests from people asking where to get the files, then asking how CLI tools work, then asking what's wrong with their files

**Comment by hadess** [comment]
> I think most folks use the "required files" feature to download pre-built ones (...after stating that they're legally ok to in their region etc)

Ha, I didn't realise this is what the feature did. I need to file bugs about that then :/

**Comment by hadess** [comment]
> Ha, I didn't realise this is what the feature did. I need to file bugs about that then :/

Closing in favour of https://github.com/neil-morrison44/pocket-sync/issues/173 and https://github.com/neil-morrison44/pocket-sync/issues/174, thanks!
